name = "Chemostat_Dynamics"
uuid = "d43f3d26-279f-4b31-985f-d16d95e3278a"
authors = ["josePereiro <jose.pereiro.lab@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
